/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace EulerSimpleLens {
  export type ResponseIRMStruct = {
    kink: BigNumberish;
    baseAPY: BigNumberish;
    kinkAPY: BigNumberish;
    maxAPY: BigNumberish;
    baseSupplyAPY: BigNumberish;
    kinkSupplyAPY: BigNumberish;
    maxSupplyAPY: BigNumberish;
  };

  export type ResponseIRMStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    kink: BigNumber;
    baseAPY: BigNumber;
    kinkAPY: BigNumber;
    maxAPY: BigNumber;
    baseSupplyAPY: BigNumber;
    kinkSupplyAPY: BigNumber;
    maxSupplyAPY: BigNumber;
  };
}

export declare namespace Storage {
  export type AssetConfigStruct = {
    eTokenAddress: string;
    borrowIsolated: boolean;
    collateralFactor: BigNumberish;
    borrowFactor: BigNumberish;
    twapWindow: BigNumberish;
  };

  export type AssetConfigStructOutput = [
    string,
    boolean,
    number,
    number,
    number
  ] & {
    eTokenAddress: string;
    borrowIsolated: boolean;
    collateralFactor: number;
    borrowFactor: number;
    twapWindow: number;
  };
}

export interface EulerSimpleLensInterface extends utils.Interface {
  functions: {
    "euler()": FunctionFragment;
    "exec()": FunctionFragment;
    "getAccountStatus(address)": FunctionFragment;
    "getDTokenBalance(address,address)": FunctionFragment;
    "getETokenBalance(address,address)": FunctionFragment;
    "getEnteredMarkets(address)": FunctionFragment;
    "getEulerAccountAllowance(address,address)": FunctionFragment;
    "getPTokenBalance(address,address)": FunctionFragment;
    "getPriceFull(address)": FunctionFragment;
    "getPricingConfig(address)": FunctionFragment;
    "getTokenInfo(address)": FunctionFragment;
    "getTotalSupplyAndDebts(address)": FunctionFragment;
    "interestAccumulator(address)": FunctionFragment;
    "interestRateModel(address)": FunctionFragment;
    "interestRates(address)": FunctionFragment;
    "irmSettings(address)": FunctionFragment;
    "markets()": FunctionFragment;
    "moduleGitCommit()": FunctionFragment;
    "reserveFee(address)": FunctionFragment;
    "underlyingToAssetConfig(address)": FunctionFragment;
    "underlyingToDToken(address)": FunctionFragment;
    "underlyingToEToken(address)": FunctionFragment;
    "underlyingToInternalTokens(address)": FunctionFragment;
    "underlyingToPToken(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "euler"
      | "exec"
      | "getAccountStatus"
      | "getDTokenBalance"
      | "getETokenBalance"
      | "getEnteredMarkets"
      | "getEulerAccountAllowance"
      | "getPTokenBalance"
      | "getPriceFull"
      | "getPricingConfig"
      | "getTokenInfo"
      | "getTotalSupplyAndDebts"
      | "interestAccumulator"
      | "interestRateModel"
      | "interestRates"
      | "irmSettings"
      | "markets"
      | "moduleGitCommit"
      | "reserveFee"
      | "underlyingToAssetConfig"
      | "underlyingToDToken"
      | "underlyingToEToken"
      | "underlyingToInternalTokens"
      | "underlyingToPToken"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "euler", values?: undefined): string;
  encodeFunctionData(functionFragment: "exec", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAccountStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDTokenBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getETokenBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEnteredMarkets",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEulerAccountAllowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPTokenBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceFull",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPricingConfig",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupplyAndDebts",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "interestAccumulator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "interestRateModel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "interestRates",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "irmSettings", values: [string]): string;
  encodeFunctionData(functionFragment: "markets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "moduleGitCommit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reserveFee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "underlyingToAssetConfig",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToDToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToEToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToInternalTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToPToken",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "euler", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exec", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getETokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEnteredMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEulerAccountAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceFull",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPricingConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupplyAndDebts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestAccumulator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestRateModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "irmSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "moduleGitCommit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserveFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToAssetConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToDToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToEToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToInternalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToPToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface EulerSimpleLens extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EulerSimpleLensInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    euler(overrides?: CallOverrides): Promise<[string]>;

    exec(overrides?: CallOverrides): Promise<[string]>;

    getAccountStatus(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        collateralValue: BigNumber;
        liabilityValue: BigNumber;
        healthScore: BigNumber;
      }
    >;

    getDTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getETokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEnteredMarkets(
      account: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getEulerAccountAllowance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPriceFull(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        twap: BigNumber;
        twapPeriod: BigNumber;
        currPrice: BigNumber;
      }
    >;

    getPricingConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & {
        pricingType: number;
        pricingParameters: number;
        pricingForwarded: string;
      }
    >;

    getTokenInfo(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { name: string; symbol: string }>;

    getTotalSupplyAndDebts(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        poolSize: BigNumber;
        totalBalances: BigNumber;
        totalBorrows: BigNumber;
        reserveBalance: BigNumber;
      }
    >;

    interestAccumulator(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    interestRateModel(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    interestRates(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        borrowSPY: BigNumber;
        borrowAPY: BigNumber;
        supplyAPY: BigNumber;
      }
    >;

    irmSettings(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [EulerSimpleLens.ResponseIRMStructOutput] & {
        r: EulerSimpleLens.ResponseIRMStructOutput;
      }
    >;

    markets(overrides?: CallOverrides): Promise<[string]>;

    moduleGitCommit(overrides?: CallOverrides): Promise<[string]>;

    reserveFee(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    underlyingToAssetConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [Storage.AssetConfigStructOutput] & {
        config: Storage.AssetConfigStructOutput;
      }
    >;

    underlyingToDToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[string] & { dToken: string }>;

    underlyingToEToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[string] & { eToken: string }>;

    underlyingToInternalTokens(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        eToken: string;
        dToken: string;
        pToken: string;
      }
    >;

    underlyingToPToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[string] & { pToken: string }>;
  };

  euler(overrides?: CallOverrides): Promise<string>;

  exec(overrides?: CallOverrides): Promise<string>;

  getAccountStatus(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      collateralValue: BigNumber;
      liabilityValue: BigNumber;
      healthScore: BigNumber;
    }
  >;

  getDTokenBalance(
    underlying: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getETokenBalance(
    underlying: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEnteredMarkets(
    account: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getEulerAccountAllowance(
    underlying: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPTokenBalance(
    underlying: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceFull(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      twap: BigNumber;
      twapPeriod: BigNumber;
      currPrice: BigNumber;
    }
  >;

  getPricingConfig(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<
    [number, number, string] & {
      pricingType: number;
      pricingParameters: number;
      pricingForwarded: string;
    }
  >;

  getTokenInfo(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<[string, string] & { name: string; symbol: string }>;

  getTotalSupplyAndDebts(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      poolSize: BigNumber;
      totalBalances: BigNumber;
      totalBorrows: BigNumber;
      reserveBalance: BigNumber;
    }
  >;

  interestAccumulator(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  interestRateModel(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  interestRates(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      borrowSPY: BigNumber;
      borrowAPY: BigNumber;
      supplyAPY: BigNumber;
    }
  >;

  irmSettings(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<EulerSimpleLens.ResponseIRMStructOutput>;

  markets(overrides?: CallOverrides): Promise<string>;

  moduleGitCommit(overrides?: CallOverrides): Promise<string>;

  reserveFee(underlying: string, overrides?: CallOverrides): Promise<number>;

  underlyingToAssetConfig(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<Storage.AssetConfigStructOutput>;

  underlyingToDToken(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<string>;

  underlyingToEToken(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<string>;

  underlyingToInternalTokens(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      eToken: string;
      dToken: string;
      pToken: string;
    }
  >;

  underlyingToPToken(
    underlying: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    euler(overrides?: CallOverrides): Promise<string>;

    exec(overrides?: CallOverrides): Promise<string>;

    getAccountStatus(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        collateralValue: BigNumber;
        liabilityValue: BigNumber;
        healthScore: BigNumber;
      }
    >;

    getDTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getETokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEnteredMarkets(
      account: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getEulerAccountAllowance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceFull(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        twap: BigNumber;
        twapPeriod: BigNumber;
        currPrice: BigNumber;
      }
    >;

    getPricingConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & {
        pricingType: number;
        pricingParameters: number;
        pricingForwarded: string;
      }
    >;

    getTokenInfo(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { name: string; symbol: string }>;

    getTotalSupplyAndDebts(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        poolSize: BigNumber;
        totalBalances: BigNumber;
        totalBorrows: BigNumber;
        reserveBalance: BigNumber;
      }
    >;

    interestAccumulator(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestRateModel(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestRates(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        borrowSPY: BigNumber;
        borrowAPY: BigNumber;
        supplyAPY: BigNumber;
      }
    >;

    irmSettings(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<EulerSimpleLens.ResponseIRMStructOutput>;

    markets(overrides?: CallOverrides): Promise<string>;

    moduleGitCommit(overrides?: CallOverrides): Promise<string>;

    reserveFee(underlying: string, overrides?: CallOverrides): Promise<number>;

    underlyingToAssetConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<Storage.AssetConfigStructOutput>;

    underlyingToDToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<string>;

    underlyingToEToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<string>;

    underlyingToInternalTokens(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        eToken: string;
        dToken: string;
        pToken: string;
      }
    >;

    underlyingToPToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    euler(overrides?: CallOverrides): Promise<BigNumber>;

    exec(overrides?: CallOverrides): Promise<BigNumber>;

    getAccountStatus(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getETokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEnteredMarkets(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEulerAccountAllowance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceFull(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPricingConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenInfo(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSupplyAndDebts(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestAccumulator(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestRateModel(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestRates(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    irmSettings(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    markets(overrides?: CallOverrides): Promise<BigNumber>;

    moduleGitCommit(overrides?: CallOverrides): Promise<BigNumber>;

    reserveFee(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    underlyingToAssetConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    underlyingToDToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    underlyingToEToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    underlyingToInternalTokens(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    underlyingToPToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    euler(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    exec(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccountStatus(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getETokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEnteredMarkets(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEulerAccountAllowance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPTokenBalance(
      underlying: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceFull(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPricingConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenInfo(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalSupplyAndDebts(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interestAccumulator(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interestRateModel(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interestRates(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    irmSettings(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    markets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    moduleGitCommit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reserveFee(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    underlyingToAssetConfig(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    underlyingToDToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    underlyingToEToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    underlyingToInternalTokens(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    underlyingToPToken(
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
