/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace EulerGeneralView {
  export type QueryStruct = {
    eulerContract: PromiseOrValue<string>;
    account: PromiseOrValue<string>;
    markets: PromiseOrValue<string>[];
  };

  export type QueryStructOutput = [string, string, string[]] & {
    eulerContract: string;
    account: string;
    markets: string[];
  };

  export type ResponseMarketStruct = {
    underlying: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    symbol: PromiseOrValue<string>;
    decimals: PromiseOrValue<BigNumberish>;
    eTokenAddr: PromiseOrValue<string>;
    dTokenAddr: PromiseOrValue<string>;
    pTokenAddr: PromiseOrValue<string>;
    config: Storage.AssetConfigStruct;
    poolSize: PromiseOrValue<BigNumberish>;
    totalBalances: PromiseOrValue<BigNumberish>;
    totalBorrows: PromiseOrValue<BigNumberish>;
    reserveBalance: PromiseOrValue<BigNumberish>;
    reserveFee: PromiseOrValue<BigNumberish>;
    borrowAPY: PromiseOrValue<BigNumberish>;
    supplyAPY: PromiseOrValue<BigNumberish>;
    twap: PromiseOrValue<BigNumberish>;
    twapPeriod: PromiseOrValue<BigNumberish>;
    currPrice: PromiseOrValue<BigNumberish>;
    pricingType: PromiseOrValue<BigNumberish>;
    pricingParameters: PromiseOrValue<BigNumberish>;
    pricingForwarded: PromiseOrValue<string>;
    underlyingBalance: PromiseOrValue<BigNumberish>;
    eulerAllowance: PromiseOrValue<BigNumberish>;
    eTokenBalance: PromiseOrValue<BigNumberish>;
    eTokenBalanceUnderlying: PromiseOrValue<BigNumberish>;
    dTokenBalance: PromiseOrValue<BigNumberish>;
    liquidityStatus: IRiskManager.LiquidityStatusStruct;
  };

  export type ResponseMarketStructOutput = [
    string,
    string,
    string,
    number,
    string,
    string,
    string,
    Storage.AssetConfigStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    IRiskManager.LiquidityStatusStructOutput
  ] & {
    underlying: string;
    name: string;
    symbol: string;
    decimals: number;
    eTokenAddr: string;
    dTokenAddr: string;
    pTokenAddr: string;
    config: Storage.AssetConfigStructOutput;
    poolSize: BigNumber;
    totalBalances: BigNumber;
    totalBorrows: BigNumber;
    reserveBalance: BigNumber;
    reserveFee: number;
    borrowAPY: BigNumber;
    supplyAPY: BigNumber;
    twap: BigNumber;
    twapPeriod: BigNumber;
    currPrice: BigNumber;
    pricingType: number;
    pricingParameters: number;
    pricingForwarded: string;
    underlyingBalance: BigNumber;
    eulerAllowance: BigNumber;
    eTokenBalance: BigNumber;
    eTokenBalanceUnderlying: BigNumber;
    dTokenBalance: BigNumber;
    liquidityStatus: IRiskManager.LiquidityStatusStructOutput;
  };

  export type ResponseStruct = {
    timestamp: PromiseOrValue<BigNumberish>;
    blockNumber: PromiseOrValue<BigNumberish>;
    markets: EulerGeneralView.ResponseMarketStruct[];
    enteredMarkets: PromiseOrValue<string>[];
  };

  export type ResponseStructOutput = [
    BigNumber,
    BigNumber,
    EulerGeneralView.ResponseMarketStructOutput[],
    string[]
  ] & {
    timestamp: BigNumber;
    blockNumber: BigNumber;
    markets: EulerGeneralView.ResponseMarketStructOutput[];
    enteredMarkets: string[];
  };

  export type ResponseAccountLiquidityStruct = {
    markets: IRiskManager.AssetLiquidityStruct[];
  };

  export type ResponseAccountLiquidityStructOutput = [
    IRiskManager.AssetLiquidityStructOutput[]
  ] & { markets: IRiskManager.AssetLiquidityStructOutput[] };

  export type QueryIRMStruct = {
    eulerContract: PromiseOrValue<string>;
    underlying: PromiseOrValue<string>;
  };

  export type QueryIRMStructOutput = [string, string] & {
    eulerContract: string;
    underlying: string;
  };

  export type ResponseIRMStruct = {
    kink: PromiseOrValue<BigNumberish>;
    baseAPY: PromiseOrValue<BigNumberish>;
    kinkAPY: PromiseOrValue<BigNumberish>;
    maxAPY: PromiseOrValue<BigNumberish>;
    baseSupplyAPY: PromiseOrValue<BigNumberish>;
    kinkSupplyAPY: PromiseOrValue<BigNumberish>;
    maxSupplyAPY: PromiseOrValue<BigNumberish>;
  };

  export type ResponseIRMStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    kink: BigNumber;
    baseAPY: BigNumber;
    kinkAPY: BigNumber;
    maxAPY: BigNumber;
    baseSupplyAPY: BigNumber;
    kinkSupplyAPY: BigNumber;
    maxSupplyAPY: BigNumber;
  };
}

export declare namespace Storage {
  export type AssetConfigStruct = {
    eTokenAddress: PromiseOrValue<string>;
    borrowIsolated: PromiseOrValue<boolean>;
    collateralFactor: PromiseOrValue<BigNumberish>;
    borrowFactor: PromiseOrValue<BigNumberish>;
    twapWindow: PromiseOrValue<BigNumberish>;
  };

  export type AssetConfigStructOutput = [
    string,
    boolean,
    number,
    number,
    number
  ] & {
    eTokenAddress: string;
    borrowIsolated: boolean;
    collateralFactor: number;
    borrowFactor: number;
    twapWindow: number;
  };
}

export declare namespace IRiskManager {
  export type LiquidityStatusStruct = {
    collateralValue: PromiseOrValue<BigNumberish>;
    liabilityValue: PromiseOrValue<BigNumberish>;
    numBorrows: PromiseOrValue<BigNumberish>;
    borrowIsolated: PromiseOrValue<boolean>;
  };

  export type LiquidityStatusStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    collateralValue: BigNumber;
    liabilityValue: BigNumber;
    numBorrows: BigNumber;
    borrowIsolated: boolean;
  };

  export type AssetLiquidityStruct = {
    underlying: PromiseOrValue<string>;
    status: IRiskManager.LiquidityStatusStruct;
  };

  export type AssetLiquidityStructOutput = [
    string,
    IRiskManager.LiquidityStatusStructOutput
  ] & { underlying: string; status: IRiskManager.LiquidityStatusStructOutput };
}

export interface EulerGeneralViewInterface extends utils.Interface {
  functions: {
    "computeAPYs(uint256,uint256,uint256,uint32)": FunctionFragment;
    "doQuery((address,address,address[]))": FunctionFragment;
    "doQueryAccountLiquidity(address,address[])": FunctionFragment;
    "doQueryBatch((address,address,address[])[])": FunctionFragment;
    "doQueryIRM((address,address))": FunctionFragment;
    "moduleGitCommit()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "computeAPYs"
      | "doQuery"
      | "doQueryAccountLiquidity"
      | "doQueryBatch"
      | "doQueryIRM"
      | "moduleGitCommit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeAPYs",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doQuery",
    values: [EulerGeneralView.QueryStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "doQueryAccountLiquidity",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "doQueryBatch",
    values: [EulerGeneralView.QueryStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "doQueryIRM",
    values: [EulerGeneralView.QueryIRMStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleGitCommit",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "computeAPYs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doQuery", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "doQueryAccountLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doQueryBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doQueryIRM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "moduleGitCommit",
    data: BytesLike
  ): Result;

  events: {};
}

export interface EulerGeneralView extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EulerGeneralViewInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    computeAPYs(
      borrowSPY: PromiseOrValue<BigNumberish>,
      totalBorrows: PromiseOrValue<BigNumberish>,
      totalBalancesUnderlying: PromiseOrValue<BigNumberish>,
      reserveFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { borrowAPY: BigNumber; supplyAPY: BigNumber }
    >;

    doQuery(
      q: EulerGeneralView.QueryStruct,
      overrides?: CallOverrides
    ): Promise<
      [EulerGeneralView.ResponseStructOutput] & {
        r: EulerGeneralView.ResponseStructOutput;
      }
    >;

    doQueryAccountLiquidity(
      eulerContract: PromiseOrValue<string>,
      addrs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [EulerGeneralView.ResponseAccountLiquidityStructOutput[]] & {
        r: EulerGeneralView.ResponseAccountLiquidityStructOutput[];
      }
    >;

    doQueryBatch(
      qs: EulerGeneralView.QueryStruct[],
      overrides?: CallOverrides
    ): Promise<
      [EulerGeneralView.ResponseStructOutput[]] & {
        r: EulerGeneralView.ResponseStructOutput[];
      }
    >;

    doQueryIRM(
      q: EulerGeneralView.QueryIRMStruct,
      overrides?: CallOverrides
    ): Promise<
      [EulerGeneralView.ResponseIRMStructOutput] & {
        r: EulerGeneralView.ResponseIRMStructOutput;
      }
    >;

    moduleGitCommit(overrides?: CallOverrides): Promise<[string]>;
  };

  computeAPYs(
    borrowSPY: PromiseOrValue<BigNumberish>,
    totalBorrows: PromiseOrValue<BigNumberish>,
    totalBalancesUnderlying: PromiseOrValue<BigNumberish>,
    reserveFee: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { borrowAPY: BigNumber; supplyAPY: BigNumber }
  >;

  doQuery(
    q: EulerGeneralView.QueryStruct,
    overrides?: CallOverrides
  ): Promise<EulerGeneralView.ResponseStructOutput>;

  doQueryAccountLiquidity(
    eulerContract: PromiseOrValue<string>,
    addrs: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<EulerGeneralView.ResponseAccountLiquidityStructOutput[]>;

  doQueryBatch(
    qs: EulerGeneralView.QueryStruct[],
    overrides?: CallOverrides
  ): Promise<EulerGeneralView.ResponseStructOutput[]>;

  doQueryIRM(
    q: EulerGeneralView.QueryIRMStruct,
    overrides?: CallOverrides
  ): Promise<EulerGeneralView.ResponseIRMStructOutput>;

  moduleGitCommit(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    computeAPYs(
      borrowSPY: PromiseOrValue<BigNumberish>,
      totalBorrows: PromiseOrValue<BigNumberish>,
      totalBalancesUnderlying: PromiseOrValue<BigNumberish>,
      reserveFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { borrowAPY: BigNumber; supplyAPY: BigNumber }
    >;

    doQuery(
      q: EulerGeneralView.QueryStruct,
      overrides?: CallOverrides
    ): Promise<EulerGeneralView.ResponseStructOutput>;

    doQueryAccountLiquidity(
      eulerContract: PromiseOrValue<string>,
      addrs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<EulerGeneralView.ResponseAccountLiquidityStructOutput[]>;

    doQueryBatch(
      qs: EulerGeneralView.QueryStruct[],
      overrides?: CallOverrides
    ): Promise<EulerGeneralView.ResponseStructOutput[]>;

    doQueryIRM(
      q: EulerGeneralView.QueryIRMStruct,
      overrides?: CallOverrides
    ): Promise<EulerGeneralView.ResponseIRMStructOutput>;

    moduleGitCommit(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    computeAPYs(
      borrowSPY: PromiseOrValue<BigNumberish>,
      totalBorrows: PromiseOrValue<BigNumberish>,
      totalBalancesUnderlying: PromiseOrValue<BigNumberish>,
      reserveFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doQuery(
      q: EulerGeneralView.QueryStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doQueryAccountLiquidity(
      eulerContract: PromiseOrValue<string>,
      addrs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doQueryBatch(
      qs: EulerGeneralView.QueryStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doQueryIRM(
      q: EulerGeneralView.QueryIRMStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    moduleGitCommit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    computeAPYs(
      borrowSPY: PromiseOrValue<BigNumberish>,
      totalBorrows: PromiseOrValue<BigNumberish>,
      totalBalancesUnderlying: PromiseOrValue<BigNumberish>,
      reserveFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doQuery(
      q: EulerGeneralView.QueryStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doQueryAccountLiquidity(
      eulerContract: PromiseOrValue<string>,
      addrs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doQueryBatch(
      qs: EulerGeneralView.QueryStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doQueryIRM(
      q: EulerGeneralView.QueryIRMStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    moduleGitCommit(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
