/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EulerGeneralView } from "./EulerGeneralView";
export type { EulerSimpleLens } from "./EulerSimpleLens";
