/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { DToken, DTokenInterface } from "../../modules/DToken";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        internalType: "bytes32",
        name: "moduleGitCommit_",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    name: "Approval",
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "owner",
      },
      {
        internalType: "address",
        name: "spender",
        indexed: true,
        type: "address",
      },
      {
        indexed: false,
        type: "uint256",
        name: "value",
        internalType: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    anonymous: false,
    type: "event",
    name: "AssetStatus",
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "totalBalances",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "totalBorrows",
      },
      {
        name: "reserveBalance",
        internalType: "uint96",
        indexed: false,
        type: "uint96",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "poolSize",
      },
      {
        internalType: "uint256",
        name: "interestAccumulator",
        indexed: false,
        type: "uint256",
      },
      {
        name: "interestRate",
        internalType: "int96",
        type: "int96",
        indexed: false,
      },
      {
        indexed: false,
        type: "uint256",
        name: "timestamp",
        internalType: "uint256",
      },
    ],
  },
  {
    name: "Borrow",
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "account",
        indexed: true,
        type: "address",
      },
      {
        indexed: true,
        type: "address",
        name: "delegate",
        internalType: "address",
      },
    ],
    name: "DelegateAverageLiquidity",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        indexed: false,
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
    name: "Deposit",
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
    ],
    name: "EnterMarket",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "ExitMarket",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "account",
        indexed: true,
        type: "address",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "Genesis",
    inputs: [],
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        type: "address",
        indexed: true,
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "recipient",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "GovConvertReserves",
  },
  {
    name: "GovSetAssetConfig",
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "tuple",
        components: [
          {
            internalType: "address",
            name: "eTokenAddress",
            type: "address",
          },
          {
            name: "borrowIsolated",
            internalType: "bool",
            type: "bool",
          },
          {
            type: "uint32",
            name: "collateralFactor",
            internalType: "uint32",
          },
          {
            type: "uint32",
            internalType: "uint32",
            name: "borrowFactor",
          },
          {
            name: "twapWindow",
            internalType: "uint24",
            type: "uint24",
          },
        ],
        internalType: "struct Storage.AssetConfig",
        name: "newConfig",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        indexed: false,
        type: "address",
        internalType: "address",
        name: "chainlinkAggregator",
      },
    ],
    name: "GovSetChainlinkPriceFeed",
  },
  {
    name: "GovSetIRM",
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "interestRateModel",
      },
      {
        type: "bytes",
        indexed: false,
        name: "resetParams",
        internalType: "bytes",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "GovSetOverride",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "liability",
        internalType: "address",
      },
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "collateral",
      },
      {
        indexed: false,
        type: "tuple",
        components: [
          {
            name: "enabled",
            internalType: "bool",
            type: "bool",
          },
          {
            internalType: "uint32",
            name: "collateralFactor",
            type: "uint32",
          },
        ],
        name: "newOverride",
        internalType: "struct Storage.OverrideConfig",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "GovSetPricingConfig",
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        internalType: "uint16",
        name: "newPricingType",
        type: "uint16",
        indexed: false,
      },
      {
        internalType: "uint32",
        name: "newPricingParameter",
        type: "uint32",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        type: "uint32",
        indexed: false,
        name: "newReserveFee",
        internalType: "uint32",
      },
    ],
    name: "GovSetReserveFee",
    type: "event",
    anonymous: false,
  },
  {
    name: "InstallerInstallModule",
    inputs: [
      {
        type: "uint256",
        indexed: true,
        name: "moduleId",
        internalType: "uint256",
      },
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "moduleImpl",
      },
      {
        indexed: false,
        type: "bytes32",
        internalType: "bytes32",
        name: "moduleGitCommit",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "InstallerSetGovernorAdmin",
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "newGovernorAdmin",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    anonymous: false,
    type: "event",
    name: "InstallerSetUpgradeAdmin",
    inputs: [
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "newUpgradeAdmin",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "Liquidation",
    inputs: [
      {
        internalType: "address",
        name: "liquidator",
        indexed: true,
        type: "address",
      },
      {
        name: "violator",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        type: "address",
        indexed: false,
        internalType: "address",
        name: "collateral",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "repay",
      },
      {
        internalType: "uint256",
        name: "yield",
        type: "uint256",
        indexed: false,
      },
      {
        name: "healthScore",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
      {
        name: "baseDiscount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
      {
        type: "uint256",
        indexed: false,
        name: "discount",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "eToken",
      },
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "dToken",
      },
    ],
    name: "MarketActivated",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "PTokenActivated",
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        name: "pToken",
        internalType: "address",
        indexed: true,
        type: "address",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PTokenUnWrap",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "account",
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "amount",
      },
    ],
    name: "PTokenWrap",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "proxy",
        internalType: "address",
      },
      {
        name: "moduleId",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "ProxyCreated",
  },
  {
    name: "Repay",
    inputs: [
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "underlying",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
        indexed: true,
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amount",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RequestBorrow",
    inputs: [
      {
        internalType: "address",
        name: "account",
        indexed: true,
        type: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "RequestBurn",
  },
  {
    name: "RequestDeposit",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amount",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "RequestDonate",
  },
  {
    anonymous: false,
    type: "event",
    name: "RequestLiquidate",
    inputs: [
      {
        internalType: "address",
        name: "liquidator",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        name: "violator",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        type: "address",
        indexed: false,
        internalType: "address",
        name: "collateral",
      },
      {
        name: "repay",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minYield",
        type: "uint256",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        type: "uint256",
        indexed: false,
        name: "amount",
        internalType: "uint256",
      },
    ],
    name: "RequestMint",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "RequestRepay",
    inputs: [
      {
        internalType: "address",
        name: "account",
        indexed: true,
        type: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "accountIn",
        type: "address",
        indexed: true,
      },
      {
        name: "accountOut",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        name: "underlyingIn",
        indexed: true,
        type: "address",
      },
      {
        name: "underlyingOut",
        internalType: "address",
        indexed: false,
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
      {
        type: "uint256",
        indexed: false,
        name: "swapType",
        internalType: "uint256",
      },
    ],
    name: "RequestSwap",
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "accountIn",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "accountOut",
        type: "address",
        indexed: true,
      },
      {
        name: "underlyingIn",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "underlyingOut",
        type: "address",
        indexed: false,
      },
      {
        indexed: false,
        type: "uint256",
        name: "amountIn",
        internalType: "uint256",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amountOut",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "mode",
      },
      {
        indexed: false,
        type: "address",
        internalType: "address",
        name: "swapHandler",
      },
    ],
    name: "RequestSwapHub",
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "accountIn",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        type: "address",
        indexed: true,
        name: "accountOut",
        internalType: "address",
      },
      {
        name: "underlyingIn",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "underlyingOut",
        indexed: false,
        type: "address",
      },
      {
        internalType: "uint256",
        name: "targetDebt",
        indexed: false,
        type: "uint256",
      },
      {
        indexed: false,
        type: "address",
        internalType: "address",
        name: "swapHandler",
      },
    ],
    name: "RequestSwapHubRepay",
  },
  {
    name: "RequestTransferDToken",
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "from",
      },
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "to",
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RequestTransferEToken",
    inputs: [
      {
        name: "from",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "to",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amount",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RequestWithdraw",
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "account",
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
    ],
    name: "TrackAverageLiquidity",
  },
  {
    anonymous: false,
    type: "event",
    name: "Transfer",
    inputs: [
      {
        name: "from",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "to",
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "value",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "UnTrackAverageLiquidity",
    inputs: [
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "account",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        name: "account",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amount",
      },
    ],
    name: "Withdraw",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "subAccountId",
        type: "uint256",
      },
      {
        type: "address",
        internalType: "address",
        name: "spender",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    name: "approveDebt",
    type: "function",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
  },
  {
    type: "function",
    outputs: [
      {
        name: "",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    stateMutability: "view",
    name: "balanceOf",
  },
  {
    outputs: [
      {
        type: "uint256",
        internalType: "uint256",
        name: "",
      },
    ],
    type: "function",
    stateMutability: "view",
    name: "balanceOfExact",
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
      },
    ],
  },
  {
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
    name: "borrow",
    inputs: [
      {
        type: "uint256",
        internalType: "uint256",
        name: "subAccountId",
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "amount",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "holder",
        type: "address",
      },
      {
        name: "spender",
        internalType: "address",
        type: "address",
      },
    ],
    name: "debtAllowance",
    stateMutability: "view",
    type: "function",
    outputs: [
      {
        name: "",
        internalType: "uint256",
        type: "uint256",
      },
    ],
  },
  {
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        type: "uint8",
        name: "",
        internalType: "uint8",
      },
    ],
    type: "function",
  },
  {
    type: "function",
    outputs: [],
    inputs: [
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
      {
        type: "bytes",
        internalType: "bytes",
        name: "data",
      },
    ],
    stateMutability: "nonpayable",
    name: "flashLoan",
  },
  {
    type: "function",
    outputs: [
      {
        type: "bytes32",
        name: "",
        internalType: "bytes32",
      },
    ],
    inputs: [],
    stateMutability: "view",
    name: "moduleGitCommit",
  },
  {
    inputs: [],
    stateMutability: "view",
    name: "moduleId",
    type: "function",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
  },
  {
    stateMutability: "view",
    name: "name",
    inputs: [],
    outputs: [
      {
        type: "string",
        internalType: "string",
        name: "",
      },
    ],
    type: "function",
  },
  {
    name: "repay",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "uint256",
        internalType: "uint256",
        name: "subAccountId",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    outputs: [],
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    stateMutability: "view",
    type: "function",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
  },
  {
    type: "function",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    inputs: [],
    stateMutability: "view",
    name: "totalSupply",
  },
  {
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    type: "function",
    name: "totalSupplyExact",
    stateMutability: "view",
    inputs: [],
  },
  {
    stateMutability: "nonpayable",
    name: "transfer",
    inputs: [
      {
        type: "address",
        name: "to",
        internalType: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    outputs: [
      {
        type: "bool",
        internalType: "bool",
        name: "",
      },
    ],
    type: "function",
  },
  {
    type: "function",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    inputs: [
      {
        name: "from",
        internalType: "address",
        type: "address",
      },
      {
        type: "address",
        internalType: "address",
        name: "to",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    name: "transferFrom",
  },
  {
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "address",
      },
    ],
    type: "function",
    stateMutability: "view",
    name: "underlyingAsset",
    inputs: [],
  },
];

export class DToken__factory {
  static readonly abi = _abi;
  static createInterface(): DTokenInterface {
    return new utils.Interface(_abi) as DTokenInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): DToken {
    return new Contract(address, _abi, signerOrProvider) as DToken;
  }
}
