/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Exec, ExecInterface } from "../../modules/Exec";

const _abi = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "bytes32",
        internalType: "bytes32",
        name: "moduleGitCommit_",
      },
    ],
  },
  {
    inputs: [
      {
        name: "simulation",
        components: [
          {
            internalType: "bool",
            type: "bool",
            name: "success",
          },
          {
            internalType: "bytes",
            type: "bytes",
            name: "result",
          },
        ],
        type: "tuple[]",
        internalType: "struct Exec.EulerBatchItemResponse[]",
      },
    ],
    name: "BatchDispatchSimulation",
    type: "error",
  },
  {
    name: "AssetStatus",
    inputs: [
      {
        name: "underlying",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        type: "uint256",
        internalType: "uint256",
        indexed: false,
        name: "totalBalances",
      },
      {
        internalType: "uint256",
        type: "uint256",
        indexed: false,
        name: "totalBorrows",
      },
      {
        internalType: "uint96",
        type: "uint96",
        name: "reserveBalance",
        indexed: false,
      },
      {
        indexed: false,
        name: "poolSize",
        type: "uint256",
        internalType: "uint256",
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "interestAccumulator",
        indexed: false,
      },
      {
        internalType: "int96",
        type: "int96",
        name: "interestRate",
        indexed: false,
      },
      {
        indexed: false,
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    name: "Borrow",
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "underlying",
      },
      {
        indexed: true,
        name: "account",
        internalType: "address",
        type: "address",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "account",
        indexed: true,
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "delegate",
      },
    ],
    name: "DelegateAverageLiquidity",
    anonymous: false,
    type: "event",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        indexed: true,
        name: "underlying",
        internalType: "address",
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "Deposit",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "underlying",
      },
      {
        indexed: true,
        name: "account",
        internalType: "address",
        type: "address",
      },
    ],
    name: "EnterMarket",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
    ],
    name: "ExitMarket",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [],
    name: "Genesis",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "underlying",
        indexed: true,
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "recipient",
      },
      {
        name: "amount",
        indexed: false,
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "GovConvertReserves",
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    name: "GovSetAssetConfig",
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "underlying",
      },
      {
        internalType: "struct Storage.AssetConfig",
        type: "tuple",
        name: "newConfig",
        indexed: false,
        components: [
          {
            type: "address",
            internalType: "address",
            name: "eTokenAddress",
          },
          {
            type: "bool",
            internalType: "bool",
            name: "borrowIsolated",
          },
          {
            name: "collateralFactor",
            internalType: "uint32",
            type: "uint32",
          },
          {
            type: "uint32",
            internalType: "uint32",
            name: "borrowFactor",
          },
          {
            name: "twapWindow",
            internalType: "uint24",
            type: "uint24",
          },
        ],
      },
    ],
  },
  {
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "underlying",
      },
      {
        type: "address",
        internalType: "address",
        name: "chainlinkAggregator",
        indexed: false,
      },
    ],
    name: "GovSetChainlinkPriceFeed",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "underlying",
      },
      {
        indexed: false,
        name: "interestRateModel",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "resetParams",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    name: "GovSetIRM",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        name: "newPricingType",
        indexed: false,
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "newPricingParameter",
        indexed: false,
        internalType: "uint32",
        type: "uint32",
      },
    ],
    name: "GovSetPricingConfig",
    anonymous: false,
    type: "event",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        type: "uint32",
        internalType: "uint32",
        name: "newReserveFee",
        indexed: false,
      },
    ],
    name: "GovSetReserveFee",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        type: "uint256",
        internalType: "uint256",
        indexed: true,
        name: "moduleId",
      },
      {
        name: "moduleImpl",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
        name: "moduleGitCommit",
      },
    ],
    name: "InstallerInstallModule",
  },
  {
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "newGovernorAdmin",
      },
    ],
    name: "InstallerSetGovernorAdmin",
    anonymous: false,
    type: "event",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        name: "newUpgradeAdmin",
        indexed: true,
        internalType: "address",
        type: "address",
      },
    ],
    name: "InstallerSetUpgradeAdmin",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        indexed: true,
        name: "liquidator",
        type: "address",
        internalType: "address",
      },
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "violator",
      },
      {
        name: "underlying",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        type: "address",
        internalType: "address",
        name: "collateral",
        indexed: false,
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "repay",
        indexed: false,
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "yield",
        indexed: false,
      },
      {
        indexed: false,
        name: "healthScore",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "baseDiscount",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "discount",
        indexed: false,
      },
    ],
    name: "Liquidation",
  },
  {
    type: "event",
    anonymous: false,
    name: "MarketActivated",
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "underlying",
        indexed: true,
      },
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "eToken",
      },
      {
        internalType: "address",
        type: "address",
        name: "dToken",
        indexed: true,
      },
    ],
  },
  {
    name: "PTokenActivated",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "pToken",
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    name: "PTokenUnWrap",
    inputs: [
      {
        name: "underlying",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        type: "uint256",
        internalType: "uint256",
        indexed: false,
        name: "amount",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PTokenWrap",
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "underlying",
      },
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "proxy",
        indexed: true,
      },
      {
        indexed: false,
        name: "moduleId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "ProxyCreated",
  },
  {
    type: "event",
    anonymous: false,
    name: "Repay",
    inputs: [
      {
        name: "underlying",
        indexed: true,
        internalType: "address",
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "RequestBorrow",
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "account",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
        indexed: false,
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "RequestBurn",
  },
  {
    name: "RequestDeposit",
    inputs: [
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "RequestDonate",
  },
  {
    anonymous: false,
    type: "event",
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "liquidator",
        indexed: true,
      },
      {
        name: "violator",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "underlying",
      },
      {
        type: "address",
        internalType: "address",
        indexed: false,
        name: "collateral",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "repay",
        indexed: false,
      },
      {
        internalType: "uint256",
        type: "uint256",
        indexed: false,
        name: "minYield",
      },
    ],
    name: "RequestLiquidate",
  },
  {
    name: "RequestMint",
    inputs: [
      {
        type: "address",
        internalType: "address",
        indexed: true,
        name: "account",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    name: "RequestRepay",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "amount",
        indexed: false,
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        name: "accountIn",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "accountOut",
      },
      {
        internalType: "address",
        type: "address",
        name: "underlyingIn",
        indexed: true,
      },
      {
        internalType: "address",
        type: "address",
        indexed: false,
        name: "underlyingOut",
      },
      {
        name: "amount",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "swapType",
        indexed: false,
      },
    ],
    name: "RequestSwap",
    anonymous: false,
    type: "event",
  },
  {
    name: "RequestSwapHub",
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "accountIn",
      },
      {
        type: "address",
        internalType: "address",
        name: "accountOut",
        indexed: true,
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "underlyingIn",
      },
      {
        indexed: false,
        name: "underlyingOut",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "uint256",
        type: "uint256",
        indexed: false,
        name: "amountIn",
      },
      {
        name: "amountOut",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "mode",
        indexed: false,
      },
      {
        internalType: "address",
        type: "address",
        name: "swapHandler",
        indexed: false,
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    name: "RequestSwapHubRepay",
    inputs: [
      {
        name: "accountIn",
        indexed: true,
        internalType: "address",
        type: "address",
      },
      {
        type: "address",
        internalType: "address",
        name: "accountOut",
        indexed: true,
      },
      {
        indexed: true,
        name: "underlyingIn",
        type: "address",
        internalType: "address",
      },
      {
        type: "address",
        internalType: "address",
        name: "underlyingOut",
        indexed: false,
      },
      {
        indexed: false,
        name: "targetDebt",
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "address",
        type: "address",
        indexed: false,
        name: "swapHandler",
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    name: "RequestTransferDToken",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "from",
        indexed: true,
      },
      {
        indexed: true,
        name: "to",
        type: "address",
        internalType: "address",
      },
      {
        type: "uint256",
        internalType: "uint256",
        indexed: false,
        name: "amount",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "RequestTransferEToken",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "from",
        indexed: true,
      },
      {
        type: "address",
        internalType: "address",
        name: "to",
        indexed: true,
      },
      {
        name: "amount",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        type: "uint256",
        internalType: "uint256",
        indexed: false,
        name: "amount",
      },
    ],
    name: "RequestWithdraw",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "account",
        indexed: true,
      },
    ],
    name: "TrackAverageLiquidity",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
    ],
    name: "UnTrackAverageLiquidity",
    anonymous: false,
    type: "event",
  },
  {
    name: "Withdraw",
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "underlying",
        indexed: true,
      },
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        indexed: false,
        internalType: "uint256",
        type: "uint256",
      },
    ],
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: "struct Exec.EulerBatchItem[]",
        type: "tuple[]",
        name: "items",
        components: [
          {
            type: "bool",
            internalType: "bool",
            name: "allowError",
          },
          {
            type: "address",
            internalType: "address",
            name: "proxyAddr",
          },
          {
            internalType: "bytes",
            type: "bytes",
            name: "data",
          },
        ],
      },
      {
        type: "address[]",
        internalType: "address[]",
        name: "deferLiquidityChecks",
      },
    ],
    outputs: [],
    name: "batchDispatch",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            name: "allowError",
            internalType: "bool",
            type: "bool",
          },
          {
            name: "proxyAddr",
            type: "address",
            internalType: "address",
          },
          {
            type: "bytes",
            internalType: "bytes",
            name: "data",
          },
        ],
        name: "items",
        internalType: "struct Exec.EulerBatchItem[]",
        type: "tuple[]",
      },
      {
        internalType: "address[]",
        type: "address[]",
        name: "deferLiquidityChecks",
      },
    ],
    outputs: [],
    name: "batchDispatchSimulate",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
      },
      {
        name: "data",
        internalType: "bytes",
        type: "bytes",
      },
    ],
    name: "deferLiquidityCheck",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [
      {
        internalType: "struct IRiskManager.AssetLiquidity[]",
        type: "tuple[]",
        components: [
          {
            name: "underlying",
            internalType: "address",
            type: "address",
          },
          {
            internalType: "struct IRiskManager.LiquidityStatus",
            type: "tuple",
            name: "status",
            components: [
              {
                name: "collateralValue",
                internalType: "uint256",
                type: "uint256",
              },
              {
                name: "liabilityValue",
                type: "uint256",
                internalType: "uint256",
              },
              {
                type: "uint256",
                internalType: "uint256",
                name: "numBorrows",
              },
              {
                internalType: "bool",
                type: "bool",
                name: "borrowIsolated",
              },
            ],
          },
        ],
        name: "assets",
      },
    ],
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "account",
      },
    ],
    name: "detailedLiquidity",
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "view",
    type: "function",
    outputs: [
      {
        name: "",
        internalType: "bytes",
        type: "bytes",
      },
    ],
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "contractAddress",
      },
      {
        type: "bytes",
        internalType: "bytes",
        name: "payload",
      },
    ],
    name: "doStaticCall",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
      },
    ],
    outputs: [
      {
        name: "",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "getAverageLiquidity",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
      },
    ],
    outputs: [
      {
        internalType: "address",
        type: "address",
        name: "",
      },
    ],
    name: "getAverageLiquidityDelegateAccount",
    stateMutability: "view",
    type: "function",
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "getAverageLiquidityWithDelegate",
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "",
      },
    ],
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getPrice",
    outputs: [
      {
        type: "uint256",
        internalType: "uint256",
        name: "twap",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "twapPeriod",
      },
    ],
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "underlying",
      },
    ],
    outputs: [
      {
        name: "twap",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "twapPeriod",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "currPrice",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "getPriceFull",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
      },
    ],
    outputs: [
      {
        type: "tuple",
        internalType: "struct IRiskManager.LiquidityStatus",
        components: [
          {
            type: "uint256",
            internalType: "uint256",
            name: "collateralValue",
          },
          {
            internalType: "uint256",
            type: "uint256",
            name: "liabilityValue",
          },
          {
            name: "numBorrows",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "borrowIsolated",
            internalType: "bool",
            type: "bool",
          },
        ],
        name: "status",
      },
    ],
    name: "liquidity",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    name: "moduleGitCommit",
  },
  {
    name: "moduleId",
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "",
      },
    ],
    inputs: [],
    type: "function",
    stateMutability: "view",
  },
  {
    outputs: [],
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "pTokenUnWrap",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    outputs: [],
    inputs: [
      {
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "pTokenWrap",
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    outputs: [],
    inputs: [
      {
        name: "subAccountId",
        internalType: "uint256",
        type: "uint256",
      },
      {
        type: "address",
        internalType: "address",
        name: "delegate",
      },
      {
        name: "onlyDelegate",
        type: "bool",
        internalType: "bool",
      },
    ],
    name: "trackAverageLiquidity",
  },
  {
    outputs: [],
    inputs: [
      {
        name: "subAccountId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "unTrackAverageLiquidity",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "value",
      },
      {
        name: "deadline",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "v",
        type: "uint8",
        internalType: "uint8",
      },
      {
        internalType: "bytes32",
        type: "bytes32",
        name: "r",
      },
      {
        internalType: "bytes32",
        type: "bytes32",
        name: "s",
      },
    ],
    outputs: [],
    name: "usePermit",
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "usePermitAllowed",
    outputs: [],
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "nonce",
      },
      {
        name: "expiry",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "allowed",
        internalType: "bool",
        type: "bool",
      },
      {
        name: "v",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "r",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "s",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    outputs: [],
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "token",
      },
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        type: "uint256",
        internalType: "uint256",
        name: "deadline",
      },
      {
        internalType: "bytes",
        type: "bytes",
        name: "signature",
      },
    ],
    name: "usePermitPacked",
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Exec__factory {
  static readonly abi = _abi;
  static createInterface(): ExecInterface {
    return new utils.Interface(_abi) as ExecInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Exec {
    return new Contract(address, _abi, signerOrProvider) as Exec;
  }
}
