/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Exec, ExecInterface } from "../../modules/Exec";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        internalType: "bytes32",
        type: "bytes32",
        name: "moduleGitCommit_",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    inputs: [
      {
        components: [
          {
            type: "bool",
            name: "success",
            internalType: "bool",
          },
          {
            internalType: "bytes",
            type: "bytes",
            name: "result",
          },
        ],
        internalType: "struct Exec.EulerBatchItemResponse[]",
        name: "simulation",
        type: "tuple[]",
      },
    ],
    name: "BatchDispatchSimulation",
    type: "error",
  },
  {
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "uint256",
        name: "totalBalances",
        internalType: "uint256",
      },
      {
        indexed: false,
        type: "uint256",
        name: "totalBorrows",
        internalType: "uint256",
      },
      {
        internalType: "uint96",
        name: "reserveBalance",
        type: "uint96",
        indexed: false,
      },
      {
        indexed: false,
        name: "poolSize",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "interestAccumulator",
        type: "uint256",
        internalType: "uint256",
        indexed: false,
      },
      {
        indexed: false,
        name: "interestRate",
        type: "int96",
        internalType: "int96",
      },
      {
        indexed: false,
        name: "timestamp",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "AssetStatus",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        name: "underlying",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "Borrow",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "DelegateAverageLiquidity",
    inputs: [
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "delegate",
        type: "address",
        indexed: true,
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "underlying",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Deposit",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "account",
      },
    ],
    type: "event",
    anonymous: false,
    name: "EnterMarket",
  },
  {
    type: "event",
    anonymous: false,
    name: "ExitMarket",
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "underlying",
        type: "address",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
        indexed: true,
      },
    ],
  },
  {
    inputs: [],
    name: "Genesis",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "underlying",
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "recipient",
        indexed: true,
      },
      {
        indexed: false,
        internalType: "uint256",
        type: "uint256",
        name: "amount",
      },
    ],
    name: "GovConvertReserves",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "tuple",
        name: "newConfig",
        internalType: "struct Storage.AssetConfig",
        components: [
          {
            internalType: "address",
            type: "address",
            name: "eTokenAddress",
          },
          {
            internalType: "bool",
            type: "bool",
            name: "borrowIsolated",
          },
          {
            internalType: "uint32",
            type: "uint32",
            name: "collateralFactor",
          },
          {
            name: "borrowFactor",
            type: "uint32",
            internalType: "uint32",
          },
          {
            internalType: "uint24",
            name: "twapWindow",
            type: "uint24",
          },
        ],
      },
    ],
    anonymous: false,
    type: "event",
    name: "GovSetAssetConfig",
  },
  {
    name: "GovSetIRM",
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "underlying",
      },
      {
        name: "interestRateModel",
        type: "uint256",
        internalType: "uint256",
        indexed: false,
      },
      {
        internalType: "bytes",
        name: "resetParams",
        type: "bytes",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        type: "uint16",
        name: "newPricingType",
      },
      {
        indexed: false,
        name: "newPricingParameter",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    name: "GovSetPricingConfig",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "underlying",
      },
      {
        indexed: false,
        type: "uint32",
        name: "newReserveFee",
        internalType: "uint32",
      },
    ],
    type: "event",
    anonymous: false,
    name: "GovSetReserveFee",
  },
  {
    type: "event",
    anonymous: false,
    name: "InstallerInstallModule",
    inputs: [
      {
        internalType: "uint256",
        name: "moduleId",
        type: "uint256",
        indexed: true,
      },
      {
        name: "moduleImpl",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: false,
        name: "moduleGitCommit",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    inputs: [
      {
        name: "newGovernorAdmin",
        type: "address",
        internalType: "address",
        indexed: true,
      },
    ],
    type: "event",
    anonymous: false,
    name: "InstallerSetGovernorAdmin",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "newUpgradeAdmin",
        indexed: true,
      },
    ],
    name: "InstallerSetUpgradeAdmin",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "liquidator",
      },
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "violator",
      },
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "underlying",
      },
      {
        indexed: false,
        type: "address",
        name: "collateral",
        internalType: "address",
      },
      {
        indexed: false,
        type: "uint256",
        name: "repay",
        internalType: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "yield",
        type: "uint256",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "healthScore",
        indexed: false,
      },
      {
        name: "baseDiscount",
        type: "uint256",
        internalType: "uint256",
        indexed: false,
      },
      {
        indexed: false,
        name: "discount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
    name: "Liquidation",
  },
  {
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "underlying",
      },
      {
        indexed: true,
        name: "eToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "dToken",
        type: "address",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
    type: "event",
    name: "MarketActivated",
  },
  {
    type: "event",
    anonymous: false,
    name: "PTokenActivated",
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "underlying",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "pToken",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PTokenUnWrap",
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "account",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "underlying",
        type: "address",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
    name: "PTokenWrap",
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "proxy",
        internalType: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        type: "uint256",
        name: "moduleId",
      },
    ],
    type: "event",
    anonymous: false,
    name: "ProxyCreated",
  },
  {
    anonymous: false,
    type: "event",
    name: "Repay",
    inputs: [
      {
        indexed: true,
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        indexed: false,
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
    name: "RequestBorrow",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "RequestBurn",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    type: "event",
    anonymous: false,
    name: "RequestDeposit",
  },
  {
    anonymous: false,
    type: "event",
    name: "RequestLiquidate",
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "liquidator",
      },
      {
        name: "violator",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: true,
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "collateral",
        indexed: false,
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "repay",
        indexed: false,
      },
      {
        name: "minYield",
        type: "uint256",
        internalType: "uint256",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
    name: "RequestMint",
  },
  {
    name: "RequestRepay",
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        type: "address",
        name: "account",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "RequestSwap",
    inputs: [
      {
        name: "accountIn",
        type: "address",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: true,
        name: "accountOut",
        type: "address",
        internalType: "address",
      },
      {
        indexed: true,
        name: "underlyingIn",
        type: "address",
        internalType: "address",
      },
      {
        indexed: false,
        internalType: "address",
        type: "address",
        name: "underlyingOut",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
        indexed: false,
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "swapType",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "from",
        indexed: true,
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
    name: "RequestTransferDToken",
  },
  {
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        indexed: true,
        type: "address",
        name: "to",
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
    name: "RequestTransferEToken",
  },
  {
    name: "RequestWithdraw",
    anonymous: false,
    type: "event",
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
        indexed: false,
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TrackAverageLiquidity",
    inputs: [
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "UnTrackAverageLiquidity",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
    ],
  },
  {
    name: "Withdraw",
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
    ],
  },
  {
    outputs: [],
    type: "function",
    name: "batchDispatch",
    inputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "allowError",
            type: "bool",
          },
          {
            name: "proxyAddr",
            type: "address",
            internalType: "address",
          },
          {
            internalType: "bytes",
            type: "bytes",
            name: "data",
          },
        ],
        internalType: "struct Exec.EulerBatchItem[]",
        type: "tuple[]",
        name: "items",
      },
      {
        name: "deferLiquidityChecks",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "tuple[]",
        name: "items",
        components: [
          {
            internalType: "bool",
            name: "allowError",
            type: "bool",
          },
          {
            internalType: "address",
            name: "proxyAddr",
            type: "address",
          },
          {
            internalType: "bytes",
            type: "bytes",
            name: "data",
          },
        ],
        internalType: "struct Exec.EulerBatchItem[]",
      },
      {
        type: "address[]",
        name: "deferLiquidityChecks",
        internalType: "address[]",
      },
    ],
    name: "batchDispatchSimulate",
    type: "function",
    outputs: [],
  },
  {
    type: "function",
    name: "deferLiquidityCheck",
    outputs: [],
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "detailedLiquidity",
    outputs: [
      {
        internalType: "struct IRiskManager.AssetLiquidity[]",
        components: [
          {
            internalType: "address",
            type: "address",
            name: "underlying",
          },
          {
            internalType: "struct IRiskManager.LiquidityStatus",
            components: [
              {
                internalType: "uint256",
                name: "collateralValue",
                type: "uint256",
              },
              {
                internalType: "uint256",
                type: "uint256",
                name: "liabilityValue",
              },
              {
                name: "numBorrows",
                type: "uint256",
                internalType: "uint256",
              },
              {
                type: "bool",
                name: "borrowIsolated",
                internalType: "bool",
              },
            ],
            name: "status",
            type: "tuple",
          },
        ],
        type: "tuple[]",
        name: "assets",
      },
    ],
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "doStaticCall",
    type: "function",
    stateMutability: "view",
    inputs: [
      {
        name: "contractAddress",
        type: "address",
        internalType: "address",
      },
      {
        type: "bytes",
        name: "payload",
        internalType: "bytes",
      },
    ],
  },
  {
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "address",
        name: "account",
        internalType: "address",
      },
    ],
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "getAverageLiquidity",
    type: "function",
  },
  {
    stateMutability: "view",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "address",
      },
    ],
    name: "getAverageLiquidityDelegateAccount",
    type: "function",
  },
  {
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "getAverageLiquidityWithDelegate",
    type: "function",
  },
  {
    name: "getPrice",
    type: "function",
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "twap",
      },
      {
        internalType: "uint256",
        name: "twapPeriod",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
      },
    ],
  },
  {
    name: "getPriceFull",
    type: "function",
    outputs: [
      {
        name: "twap",
        type: "uint256",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "twapPeriod",
        internalType: "uint256",
      },
      {
        name: "currPrice",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
    inputs: [
      {
        name: "underlying",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    name: "liquidity",
    type: "function",
    outputs: [
      {
        type: "tuple",
        name: "status",
        components: [
          {
            name: "collateralValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            internalType: "uint256",
            name: "liabilityValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "numBorrows",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "borrowIsolated",
            type: "bool",
          },
        ],
        internalType: "struct IRiskManager.LiquidityStatus",
      },
    ],
    stateMutability: "view",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "account",
      },
    ],
  },
  {
    inputs: [],
    stateMutability: "view",
    type: "function",
    name: "moduleGitCommit",
    outputs: [
      {
        internalType: "bytes32",
        type: "bytes32",
        name: "",
      },
    ],
  },
  {
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "",
      },
    ],
    type: "function",
    name: "moduleId",
    inputs: [],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pTokenUnWrap",
    outputs: [],
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        type: "address",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    outputs: [],
    type: "function",
    name: "pTokenWrap",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    inputs: [
      {
        type: "uint256",
        name: "subAccountId",
        internalType: "uint256",
      },
      {
        type: "address",
        name: "delegate",
        internalType: "address",
      },
      {
        name: "onlyDelegate",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    name: "trackAverageLiquidity",
    outputs: [],
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "subAccountId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    name: "unTrackAverageLiquidity",
    outputs: [],
  },
  {
    outputs: [],
    name: "usePermit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "address",
        name: "token",
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        name: "v",
        type: "uint8",
        internalType: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
  },
  {
    stateMutability: "nonpayable",
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        name: "nonce",
        type: "uint256",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "expiry",
        internalType: "uint256",
      },
      {
        name: "allowed",
        type: "bool",
        internalType: "bool",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        type: "bytes32",
        name: "r",
        internalType: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    outputs: [],
    name: "usePermitAllowed",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        type: "uint256",
        name: "value",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "deadline",
        internalType: "uint256",
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    outputs: [],
    type: "function",
    name: "usePermitPacked",
  },
];

export class Exec__factory {
  static readonly abi = _abi;
  static createInterface(): ExecInterface {
    return new utils.Interface(_abi) as ExecInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Exec {
    return new Contract(address, _abi, signerOrProvider) as Exec;
  }
}
