/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Liquidation,
  LiquidationInterface,
} from "../../modules/Liquidation";

const _abi = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      {
        internalType: "bytes32",
        type: "bytes32",
        name: "moduleGitCommit_",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        internalType: "uint256",
        indexed: false,
        name: "totalBalances",
        type: "uint256",
      },
      {
        name: "totalBorrows",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "uint96",
        name: "reserveBalance",
        indexed: false,
        type: "uint96",
      },
      {
        internalType: "uint256",
        type: "uint256",
        indexed: false,
        name: "poolSize",
      },
      {
        internalType: "uint256",
        name: "interestAccumulator",
        indexed: false,
        type: "uint256",
      },
      {
        internalType: "int96",
        name: "interestRate",
        indexed: false,
        type: "int96",
      },
      {
        internalType: "uint256",
        type: "uint256",
        indexed: false,
        name: "timestamp",
      },
    ],
    anonymous: false,
    type: "event",
    name: "AssetStatus",
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "underlying",
        internalType: "address",
      },
      {
        type: "address",
        name: "account",
        indexed: true,
        internalType: "address",
      },
      {
        internalType: "uint256",
        indexed: false,
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Borrow",
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    name: "DelegateAverageLiquidity",
    inputs: [
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "delegate",
        indexed: true,
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "Deposit",
    anonymous: false,
    type: "event",
  },
  {
    name: "EnterMarket",
    anonymous: false,
    type: "event",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "underlying",
        internalType: "address",
      },
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    name: "ExitMarket",
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        type: "address",
        name: "account",
        indexed: true,
        internalType: "address",
      },
    ],
  },
  {
    name: "Genesis",
    type: "event",
    anonymous: false,
    inputs: [],
  },
  {
    anonymous: false,
    type: "event",
    name: "GovConvertReserves",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "underlying",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "recipient",
      },
      {
        type: "uint256",
        indexed: false,
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "eTokenAddress",
            type: "address",
          },
          {
            internalType: "bool",
            type: "bool",
            name: "borrowIsolated",
          },
          {
            internalType: "uint32",
            type: "uint32",
            name: "collateralFactor",
          },
          {
            name: "borrowFactor",
            type: "uint32",
            internalType: "uint32",
          },
          {
            type: "uint24",
            name: "twapWindow",
            internalType: "uint24",
          },
        ],
        internalType: "struct Storage.AssetConfig",
        type: "tuple",
        indexed: false,
        name: "newConfig",
      },
    ],
    name: "GovSetAssetConfig",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        internalType: "address",
        type: "address",
        indexed: false,
        name: "chainlinkAggregator",
      },
    ],
    name: "GovSetChainlinkPriceFeed",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "underlying",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "interestRateModel",
        indexed: false,
        internalType: "uint256",
      },
      {
        internalType: "bytes",
        type: "bytes",
        indexed: false,
        name: "resetParams",
      },
    ],
    anonymous: false,
    type: "event",
    name: "GovSetIRM",
  },
  {
    anonymous: false,
    type: "event",
    name: "GovSetOverride",
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "liability",
      },
      {
        type: "address",
        name: "collateral",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOverride",
        indexed: false,
        type: "tuple",
        internalType: "struct Storage.OverrideConfig",
        components: [
          {
            type: "bool",
            name: "enabled",
            internalType: "bool",
          },
          {
            internalType: "uint32",
            name: "collateralFactor",
            type: "uint32",
          },
        ],
      },
    ],
  },
  {
    name: "GovSetPricingConfig",
    anonymous: false,
    type: "event",
    inputs: [
      {
        type: "address",
        name: "underlying",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newPricingType",
        indexed: false,
        type: "uint16",
        internalType: "uint16",
      },
      {
        indexed: false,
        name: "newPricingParameter",
        type: "uint32",
        internalType: "uint32",
      },
    ],
  },
  {
    name: "GovSetReserveFee",
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        internalType: "uint32",
        type: "uint32",
        indexed: false,
        name: "newReserveFee",
      },
    ],
  },
  {
    name: "InstallerInstallModule",
    anonymous: false,
    type: "event",
    inputs: [
      {
        type: "uint256",
        indexed: true,
        name: "moduleId",
        internalType: "uint256",
      },
      {
        type: "address",
        name: "moduleImpl",
        indexed: true,
        internalType: "address",
      },
      {
        internalType: "bytes32",
        indexed: false,
        name: "moduleGitCommit",
        type: "bytes32",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "newGovernorAdmin",
        indexed: true,
      },
    ],
    name: "InstallerSetGovernorAdmin",
    anonymous: false,
    type: "event",
  },
  {
    name: "InstallerSetUpgradeAdmin",
    type: "event",
    anonymous: false,
    inputs: [
      {
        type: "address",
        name: "newUpgradeAdmin",
        indexed: true,
        internalType: "address",
      },
    ],
  },
  {
    name: "Liquidation",
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "liquidator",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "violator",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "underlying",
      },
      {
        indexed: false,
        name: "collateral",
        type: "address",
        internalType: "address",
      },
      {
        indexed: false,
        name: "repay",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "yield",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
      {
        type: "uint256",
        indexed: false,
        name: "healthScore",
        internalType: "uint256",
      },
      {
        type: "uint256",
        indexed: false,
        name: "baseDiscount",
        internalType: "uint256",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "discount",
        indexed: false,
      },
    ],
  },
  {
    name: "MarketActivated",
    type: "event",
    anonymous: false,
    inputs: [
      {
        type: "address",
        name: "underlying",
        indexed: true,
        internalType: "address",
      },
      {
        indexed: true,
        name: "eToken",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "dToken",
        indexed: true,
        type: "address",
      },
    ],
  },
  {
    name: "PTokenActivated",
    anonymous: false,
    type: "event",
    inputs: [
      {
        indexed: true,
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "pToken",
        indexed: true,
        type: "address",
      },
    ],
  },
  {
    name: "PTokenUnWrap",
    anonymous: false,
    type: "event",
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "amount",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        type: "address",
        name: "underlying",
        indexed: true,
        internalType: "address",
      },
      {
        internalType: "address",
        name: "account",
        indexed: true,
        type: "address",
      },
      {
        internalType: "uint256",
        indexed: false,
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PTokenWrap",
    anonymous: false,
    type: "event",
  },
  {
    name: "ProxyCreated",
    anonymous: false,
    type: "event",
    inputs: [
      {
        name: "proxy",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        name: "moduleId",
        indexed: false,
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "underlying",
      },
      {
        internalType: "address",
        type: "address",
        name: "account",
        indexed: true,
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "Repay",
    anonymous: false,
    type: "event",
  },
  {
    name: "RequestBorrow",
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "account",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    name: "RequestBurn",
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        internalType: "uint256",
        type: "uint256",
        indexed: false,
        name: "amount",
      },
    ],
  },
  {
    inputs: [
      {
        name: "account",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "amount",
        indexed: false,
        internalType: "uint256",
      },
    ],
    name: "RequestDeposit",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        indexed: true,
        type: "address",
      },
      {
        type: "uint256",
        name: "amount",
        indexed: false,
        internalType: "uint256",
      },
    ],
    name: "RequestDonate",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        type: "address",
        name: "liquidator",
        indexed: true,
        internalType: "address",
      },
      {
        internalType: "address",
        name: "violator",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        indexed: true,
        name: "underlying",
        type: "address",
      },
      {
        indexed: false,
        name: "collateral",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "uint256",
        indexed: false,
        name: "repay",
        type: "uint256",
      },
      {
        type: "uint256",
        name: "minYield",
        indexed: false,
        internalType: "uint256",
      },
    ],
    name: "RequestLiquidate",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "account",
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
    name: "RequestMint",
  },
  {
    type: "event",
    anonymous: false,
    name: "RequestRepay",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "amount",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "accountIn",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "accountOut",
        indexed: true,
      },
      {
        internalType: "address",
        indexed: true,
        name: "underlyingIn",
        type: "address",
      },
      {
        type: "address",
        name: "underlyingOut",
        indexed: false,
        internalType: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
      {
        type: "uint256",
        name: "swapType",
        indexed: false,
        internalType: "uint256",
      },
    ],
    name: "RequestSwap",
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    name: "RequestSwapHub",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "accountIn",
        internalType: "address",
      },
      {
        name: "accountOut",
        indexed: true,
        type: "address",
        internalType: "address",
      },
      {
        type: "address",
        indexed: true,
        name: "underlyingIn",
        internalType: "address",
      },
      {
        type: "address",
        name: "underlyingOut",
        indexed: false,
        internalType: "address",
      },
      {
        indexed: false,
        name: "amountIn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amountOut",
        indexed: false,
      },
      {
        indexed: false,
        name: "mode",
        type: "uint256",
        internalType: "uint256",
      },
      {
        internalType: "address",
        name: "swapHandler",
        indexed: false,
        type: "address",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "accountIn",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "accountOut",
      },
      {
        internalType: "address",
        type: "address",
        name: "underlyingIn",
        indexed: true,
      },
      {
        type: "address",
        indexed: false,
        name: "underlyingOut",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "targetDebt",
        indexed: false,
        internalType: "uint256",
      },
      {
        internalType: "address",
        name: "swapHandler",
        indexed: false,
        type: "address",
      },
    ],
    anonymous: false,
    type: "event",
    name: "RequestSwapHubRepay",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        indexed: true,
        type: "address",
      },
      {
        internalType: "address",
        type: "address",
        indexed: true,
        name: "to",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
        indexed: false,
      },
    ],
    name: "RequestTransferDToken",
    type: "event",
    anonymous: false,
  },
  {
    name: "RequestTransferEToken",
    anonymous: false,
    type: "event",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "from",
        indexed: true,
      },
      {
        indexed: true,
        name: "to",
        type: "address",
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [
      {
        internalType: "address",
        indexed: true,
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    type: "event",
    anonymous: false,
    name: "RequestWithdraw",
  },
  {
    anonymous: false,
    type: "event",
    name: "TrackAverageLiquidity",
    inputs: [
      {
        internalType: "address",
        indexed: true,
        name: "account",
        type: "address",
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    name: "UnTrackAverageLiquidity",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "underlying",
        indexed: true,
      },
      {
        type: "address",
        name: "account",
        indexed: true,
        internalType: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [],
    stateMutability: "view",
    type: "function",
    name: "DISCOUNT_BOOSTER_SLOPE",
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "",
      },
    ],
    name: "MAXIMUM_BOOSTER_DISCOUNT",
    inputs: [],
  },
  {
    name: "MAXIMUM_DISCOUNT",
    outputs: [
      {
        internalType: "uint256",
        type: "uint256",
        name: "",
      },
    ],
    type: "function",
    stateMutability: "view",
    inputs: [],
  },
  {
    inputs: [],
    type: "function",
    stateMutability: "view",
    name: "TARGET_HEALTH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
  },
  {
    inputs: [],
    stateMutability: "view",
    type: "function",
    name: "UNDERLYING_RESERVES_FEE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      {
        internalType: "struct Liquidation.LiquidationOpportunity",
        components: [
          {
            internalType: "uint256",
            type: "uint256",
            name: "repay",
          },
          {
            internalType: "uint256",
            type: "uint256",
            name: "yield",
          },
          {
            name: "healthScore",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "baseDiscount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            type: "uint256",
            name: "discount",
            internalType: "uint256",
          },
          {
            name: "conversionRate",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        name: "liqOpp",
        type: "tuple",
      },
    ],
    name: "checkLiquidation",
    inputs: [
      {
        name: "liquidator",
        type: "address",
        internalType: "address",
      },
      {
        name: "violator",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "underlying",
        type: "address",
      },
      {
        name: "collateral",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    outputs: [],
    name: "liquidate",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "violator",
      },
      {
        name: "underlying",
        type: "address",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "collateral",
      },
      {
        type: "uint256",
        name: "repay",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "minYield",
        internalType: "uint256",
      },
    ],
  },
  {
    inputs: [],
    outputs: [
      {
        type: "bytes32",
        name: "",
        internalType: "bytes32",
      },
    ],
    name: "moduleGitCommit",
    stateMutability: "view",
    type: "function",
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    name: "moduleId",
    inputs: [],
  },
];

export class Liquidation__factory {
  static readonly abi = _abi;
  static createInterface(): LiquidationInterface {
    return new utils.Interface(_abi) as LiquidationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Liquidation {
    return new Contract(address, _abi, signerOrProvider) as Liquidation;
  }
}
