/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Swap, SwapInterface } from "../../modules/Swap";

const _abi = [
  {
    inputs: [
      {
        name: "moduleGitCommit_",
        internalType: "bytes32",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "uniswapRouter_",
        type: "address",
      },
      {
        type: "address",
        name: "oneInch_",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "totalBalances",
      },
      {
        name: "totalBorrows",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        type: "uint96",
        indexed: false,
        name: "reserveBalance",
        internalType: "uint96",
      },
      {
        indexed: false,
        type: "uint256",
        name: "poolSize",
        internalType: "uint256",
      },
      {
        indexed: false,
        type: "uint256",
        name: "interestAccumulator",
        internalType: "uint256",
      },
      {
        name: "interestRate",
        internalType: "int96",
        indexed: false,
        type: "int96",
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "timestamp",
      },
    ],
    name: "AssetStatus",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "Borrow",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "account",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "delegate",
        type: "address",
        indexed: true,
      },
    ],
    name: "DelegateAverageLiquidity",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "account",
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        type: "address",
        indexed: true,
      },
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
    ],
    name: "EnterMarket",
  },
  {
    anonymous: false,
    type: "event",
    name: "ExitMarket",
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
  },
  {
    name: "Genesis",
    inputs: [],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "GovConvertReserves",
  },
  {
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        internalType: "struct Storage.AssetConfig",
        name: "newConfig",
        type: "tuple",
        components: [
          {
            type: "address",
            internalType: "address",
            name: "eTokenAddress",
          },
          {
            type: "bool",
            name: "borrowIsolated",
            internalType: "bool",
          },
          {
            name: "collateralFactor",
            internalType: "uint32",
            type: "uint32",
          },
          {
            type: "uint32",
            name: "borrowFactor",
            internalType: "uint32",
          },
          {
            type: "uint24",
            internalType: "uint24",
            name: "twapWindow",
          },
        ],
        indexed: false,
      },
    ],
    name: "GovSetAssetConfig",
    type: "event",
    anonymous: false,
  },
  {
    name: "GovSetChainlinkPriceFeed",
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        indexed: false,
        type: "address",
        internalType: "address",
        name: "chainlinkAggregator",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "GovSetIRM",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        type: "uint256",
        indexed: false,
        name: "interestRateModel",
        internalType: "uint256",
      },
      {
        type: "bytes",
        indexed: false,
        name: "resetParams",
        internalType: "bytes",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "liability",
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "collateral",
      },
      {
        internalType: "struct Storage.OverrideConfig",
        name: "newOverride",
        type: "tuple",
        components: [
          {
            internalType: "bool",
            name: "enabled",
            type: "bool",
          },
          {
            type: "uint32",
            name: "collateralFactor",
            internalType: "uint32",
          },
        ],
        indexed: false,
      },
    ],
    name: "GovSetOverride",
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "underlying",
      },
      {
        indexed: false,
        type: "uint16",
        internalType: "uint16",
        name: "newPricingType",
      },
      {
        type: "uint32",
        indexed: false,
        name: "newPricingParameter",
        internalType: "uint32",
      },
    ],
    name: "GovSetPricingConfig",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "underlying",
      },
      {
        indexed: false,
        type: "uint32",
        name: "newReserveFee",
        internalType: "uint32",
      },
    ],
    name: "GovSetReserveFee",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "InstallerInstallModule",
    inputs: [
      {
        type: "uint256",
        indexed: true,
        name: "moduleId",
        internalType: "uint256",
      },
      {
        name: "moduleImpl",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
        name: "moduleGitCommit",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "InstallerSetGovernorAdmin",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "newGovernorAdmin",
        internalType: "address",
      },
    ],
  },
  {
    name: "InstallerSetUpgradeAdmin",
    inputs: [
      {
        name: "newUpgradeAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "liquidator",
        internalType: "address",
      },
      {
        name: "violator",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        name: "underlying",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "address",
        name: "collateral",
        internalType: "address",
      },
      {
        type: "uint256",
        indexed: false,
        name: "repay",
        internalType: "uint256",
      },
      {
        type: "uint256",
        indexed: false,
        name: "yield",
        internalType: "uint256",
      },
      {
        indexed: false,
        type: "uint256",
        name: "healthScore",
        internalType: "uint256",
      },
      {
        name: "baseDiscount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "discount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Liquidation",
    type: "event",
    anonymous: false,
  },
  {
    name: "MarketActivated",
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "eToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "dToken",
        internalType: "address",
        indexed: true,
        type: "address",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        internalType: "address",
        name: "underlying",
        indexed: true,
        type: "address",
      },
      {
        name: "pToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "PTokenActivated",
  },
  {
    name: "PTokenUnWrap",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "underlying",
        internalType: "address",
      },
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PTokenWrap",
    type: "event",
    anonymous: false,
  },
  {
    anonymous: false,
    type: "event",
    name: "ProxyCreated",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "proxy",
        internalType: "address",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "moduleId",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "Repay",
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "account",
      },
      {
        indexed: false,
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "RequestBorrow",
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "amount",
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "account",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amount",
      },
    ],
    name: "RequestBurn",
    type: "event",
    anonymous: false,
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "account",
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "RequestDeposit",
    type: "event",
    anonymous: false,
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "RequestDonate",
  },
  {
    name: "RequestLiquidate",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "liquidator",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "violator",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "underlying",
        type: "address",
        indexed: true,
      },
      {
        name: "collateral",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "repay",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minYield",
        type: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RequestMint",
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        name: "account",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        type: "uint256",
        indexed: false,
        internalType: "uint256",
        name: "amount",
      },
    ],
    name: "RequestRepay",
    type: "event",
    anonymous: false,
  },
  {
    name: "RequestSwap",
    inputs: [
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "accountIn",
      },
      {
        internalType: "address",
        name: "accountOut",
        type: "address",
        indexed: true,
      },
      {
        type: "address",
        indexed: true,
        internalType: "address",
        name: "underlyingIn",
      },
      {
        type: "address",
        indexed: false,
        name: "underlyingOut",
        internalType: "address",
      },
      {
        indexed: false,
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
      {
        name: "swapType",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        type: "address",
        internalType: "address",
        name: "accountIn",
      },
      {
        internalType: "address",
        name: "accountOut",
        type: "address",
        indexed: true,
      },
      {
        internalType: "address",
        name: "underlyingIn",
        indexed: true,
        type: "address",
      },
      {
        name: "underlyingOut",
        internalType: "address",
        indexed: false,
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        indexed: false,
        type: "uint256",
      },
      {
        indexed: false,
        type: "uint256",
        internalType: "uint256",
        name: "amountOut",
      },
      {
        internalType: "uint256",
        name: "mode",
        type: "uint256",
        indexed: false,
      },
      {
        type: "address",
        indexed: false,
        name: "swapHandler",
        internalType: "address",
      },
    ],
    name: "RequestSwapHub",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "accountIn",
        type: "address",
        indexed: true,
      },
      {
        name: "accountOut",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "underlyingIn",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        indexed: false,
        type: "address",
        name: "underlyingOut",
        internalType: "address",
      },
      {
        internalType: "uint256",
        name: "targetDebt",
        indexed: false,
        type: "uint256",
      },
      {
        type: "address",
        indexed: false,
        name: "swapHandler",
        internalType: "address",
      },
    ],
    name: "RequestSwapHubRepay",
    type: "event",
    anonymous: false,
  },
  {
    name: "RequestTransferDToken",
    inputs: [
      {
        name: "from",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "to",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    anonymous: false,
    type: "event",
    name: "RequestTransferEToken",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "from",
        internalType: "address",
      },
      {
        name: "to",
        internalType: "address",
        indexed: true,
        type: "address",
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
  },
  {
    anonymous: false,
    type: "event",
    name: "RequestWithdraw",
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        type: "uint256",
        indexed: false,
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    name: "TrackAverageLiquidity",
    inputs: [
      {
        type: "address",
        indexed: true,
        name: "account",
        internalType: "address",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "UnTrackAverageLiquidity",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "account",
        internalType: "address",
      },
    ],
    anonymous: false,
    type: "event",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "underlying",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        indexed: false,
        type: "uint256",
      },
    ],
    name: "Withdraw",
  },
  {
    inputs: [],
    name: "moduleGitCommit",
    stateMutability: "view",
    type: "function",
    outputs: [
      {
        type: "bytes32",
        internalType: "bytes32",
        name: "",
      },
    ],
  },
  {
    type: "function",
    outputs: [
      {
        name: "",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    inputs: [],
    name: "moduleId",
    stateMutability: "view",
  },
  {
    inputs: [],
    name: "oneInch",
    stateMutability: "view",
    type: "function",
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "address",
      },
    ],
  },
  {
    inputs: [
      {
        name: "params",
        internalType: "struct Swap.Swap1InchParams",
        type: "tuple",
        components: [
          {
            internalType: "uint256",
            name: "subAccountIdIn",
            type: "uint256",
          },
          {
            type: "uint256",
            name: "subAccountIdOut",
            internalType: "uint256",
          },
          {
            name: "underlyingIn",
            internalType: "address",
            type: "address",
          },
          {
            name: "underlyingOut",
            internalType: "address",
            type: "address",
          },
          {
            name: "amount",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "uint256",
            name: "amountOutMinimum",
            internalType: "uint256",
          },
          {
            internalType: "bytes",
            name: "payload",
            type: "bytes",
          },
        ],
      },
    ],
    name: "swap1Inch",
    stateMutability: "nonpayable",
    type: "function",
    outputs: [],
  },
  {
    name: "swapAndRepayUni",
    stateMutability: "nonpayable",
    inputs: [
      {
        components: [
          {
            type: "uint256",
            internalType: "uint256",
            name: "subAccountIdIn",
          },
          {
            type: "uint256",
            name: "subAccountIdOut",
            internalType: "uint256",
          },
          {
            type: "uint256",
            name: "amountOut",
            internalType: "uint256",
          },
          {
            type: "uint256",
            internalType: "uint256",
            name: "amountInMaximum",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "path",
            type: "bytes",
          },
        ],
        type: "tuple",
        internalType: "struct Swap.SwapUniExactOutputParams",
        name: "params",
      },
      {
        internalType: "uint256",
        name: "targetDebt",
        type: "uint256",
      },
    ],
    outputs: [],
    type: "function",
  },
  {
    type: "function",
    outputs: [],
    inputs: [
      {
        name: "params",
        internalType: "struct Swap.SwapUniExactOutputSingleParams",
        type: "tuple",
        components: [
          {
            name: "subAccountIdIn",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "uint256",
            internalType: "uint256",
            name: "subAccountIdOut",
          },
          {
            type: "address",
            name: "underlyingIn",
            internalType: "address",
          },
          {
            internalType: "address",
            name: "underlyingOut",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountOut",
            type: "uint256",
          },
          {
            name: "amountInMaximum",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "uint256",
            name: "deadline",
            internalType: "uint256",
          },
          {
            type: "uint24",
            internalType: "uint24",
            name: "fee",
          },
          {
            name: "sqrtPriceLimitX96",
            internalType: "uint160",
            type: "uint160",
          },
        ],
      },
      {
        type: "uint256",
        name: "targetDebt",
        internalType: "uint256",
      },
    ],
    name: "swapAndRepayUniSingle",
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    outputs: [],
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "subAccountIdIn",
            type: "uint256",
          },
          {
            type: "uint256",
            internalType: "uint256",
            name: "subAccountIdOut",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMinimum",
            type: "uint256",
          },
          {
            type: "uint256",
            name: "deadline",
            internalType: "uint256",
          },
          {
            name: "path",
            internalType: "bytes",
            type: "bytes",
          },
        ],
        type: "tuple",
        name: "params",
        internalType: "struct Swap.SwapUniExactInputParams",
      },
    ],
    stateMutability: "nonpayable",
    name: "swapUniExactInput",
  },
  {
    stateMutability: "nonpayable",
    name: "swapUniExactInputSingle",
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "subAccountIdIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "subAccountIdOut",
            type: "uint256",
          },
          {
            type: "address",
            internalType: "address",
            name: "underlyingIn",
          },
          {
            name: "underlyingOut",
            internalType: "address",
            type: "address",
          },
          {
            type: "uint256",
            internalType: "uint256",
            name: "amountIn",
          },
          {
            internalType: "uint256",
            name: "amountOutMinimum",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            name: "fee",
            internalType: "uint24",
            type: "uint24",
          },
          {
            type: "uint160",
            internalType: "uint160",
            name: "sqrtPriceLimitX96",
          },
        ],
        type: "tuple",
        name: "params",
        internalType: "struct Swap.SwapUniExactInputSingleParams",
      },
    ],
    outputs: [],
    type: "function",
  },
  {
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
    name: "swapUniExactOutput",
    inputs: [
      {
        type: "tuple",
        components: [
          {
            type: "uint256",
            name: "subAccountIdIn",
            internalType: "uint256",
          },
          {
            name: "subAccountIdOut",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "uint256",
            internalType: "uint256",
            name: "amountOut",
          },
          {
            name: "amountInMaximum",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "uint256",
            name: "deadline",
            internalType: "uint256",
          },
          {
            type: "bytes",
            name: "path",
            internalType: "bytes",
          },
        ],
        name: "params",
        internalType: "struct Swap.SwapUniExactOutputParams",
      },
    ],
  },
  {
    type: "function",
    outputs: [],
    inputs: [
      {
        name: "params",
        internalType: "struct Swap.SwapUniExactOutputSingleParams",
        type: "tuple",
        components: [
          {
            name: "subAccountIdIn",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "subAccountIdOut",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "address",
            name: "underlyingIn",
            internalType: "address",
          },
          {
            name: "underlyingOut",
            internalType: "address",
            type: "address",
          },
          {
            name: "amountOut",
            internalType: "uint256",
            type: "uint256",
          },
          {
            type: "uint256",
            name: "amountInMaximum",
            internalType: "uint256",
          },
          {
            type: "uint256",
            name: "deadline",
            internalType: "uint256",
          },
          {
            type: "uint24",
            name: "fee",
            internalType: "uint24",
          },
          {
            type: "uint160",
            name: "sqrtPriceLimitX96",
            internalType: "uint160",
          },
        ],
      },
    ],
    name: "swapUniExactOutputSingle",
    stateMutability: "nonpayable",
  },
  {
    stateMutability: "view",
    name: "uniswapRouter",
    inputs: [],
    outputs: [
      {
        type: "address",
        internalType: "address",
        name: "",
      },
    ],
    type: "function",
  },
];

export class Swap__factory {
  static readonly abi = _abi;
  static createInterface(): SwapInterface {
    return new utils.Interface(_abi) as SwapInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Swap {
    return new Contract(address, _abi, signerOrProvider) as Swap;
  }
}
