/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { PToken, PTokenInterface } from "../PToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "euler_",
        type: "address",
      },
      {
        type: "address",
        name: "underlying_",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    type: "event",
    anonymous: false,
    name: "Approval",
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "owner",
        internalType: "address",
      },
      {
        type: "address",
        name: "spender",
        internalType: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "value",
        indexed: false,
      },
    ],
  },
  {
    inputs: [
      {
        indexed: true,
        type: "address",
        name: "from",
        internalType: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
        indexed: true,
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Transfer",
    anonymous: false,
    type: "event",
  },
  {
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    type: "function",
    name: "allowance",
    inputs: [
      {
        internalType: "address",
        type: "address",
        name: "holder",
      },
      {
        type: "address",
        name: "spender",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    name: "approve",
    type: "function",
    outputs: [
      {
        type: "bool",
        name: "",
        internalType: "bool",
      },
    ],
    stateMutability: "nonpayable",
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    stateMutability: "view",
    inputs: [
      {
        type: "address",
        name: "who",
        internalType: "address",
      },
    ],
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "balanceOf",
    type: "function",
  },
  {
    type: "function",
    name: "claimSurplus",
    outputs: [],
    inputs: [
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    stateMutability: "view",
    inputs: [],
    name: "decimals",
    type: "function",
    outputs: [
      {
        type: "uint8",
        name: "",
        internalType: "uint8",
      },
    ],
  },
  {
    outputs: [],
    type: "function",
    name: "forceUnwrap",
    inputs: [
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    name: "name",
    type: "function",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    inputs: [],
  },
  {
    outputs: [
      {
        internalType: "string",
        type: "string",
        name: "",
      },
    ],
    name: "symbol",
    type: "function",
    stateMutability: "view",
    inputs: [],
  },
  {
    stateMutability: "view",
    inputs: [],
    name: "totalSupply",
    type: "function",
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    name: "transfer",
    type: "function",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
      },
    ],
  },
  {
    name: "transferFrom",
    type: "function",
    outputs: [
      {
        type: "bool",
        name: "",
        internalType: "bool",
      },
    ],
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
      },
      {
        internalType: "address",
        type: "address",
        name: "recipient",
      },
      {
        internalType: "uint256",
        type: "uint256",
        name: "amount",
      },
    ],
  },
  {
    inputs: [],
    stateMutability: "view",
    type: "function",
    name: "underlying",
    outputs: [
      {
        internalType: "address",
        type: "address",
        name: "",
      },
    ],
  },
  {
    outputs: [],
    type: "function",
    name: "unwrap",
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    name: "wrap",
    type: "function",
  },
];

export class PToken__factory {
  static readonly abi = _abi;
  static createInterface(): PTokenInterface {
    return new utils.Interface(_abi) as PTokenInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): PToken {
    return new Contract(address, _abi, signerOrProvider) as PToken;
  }
}
