/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace EulStakes {
  export type StakeOpStruct = { underlying: string; amount: BigNumberish };

  export type StakeOpStructOutput = [string, BigNumber] & {
    underlying: string;
    amount: BigNumber;
  };
}

export interface EulStakesInterface extends utils.Interface {
  functions: {
    "eul()": FunctionFragment;
    "name()": FunctionFragment;
    "stake((address,int256)[])": FunctionFragment;
    "stakeGift(address,address,uint256)": FunctionFragment;
    "stakePermit((address,int256)[],uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "staked(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "eul"
      | "name"
      | "stake"
      | "stakeGift"
      | "stakePermit"
      | "staked"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "eul", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [EulStakes.StakeOpStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeGift",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakePermit",
    values: [
      EulStakes.StakeOpStruct[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "staked",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "eul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeGift", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakePermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "staked", data: BytesLike): Result;

  events: {
    "Stake(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Stake"): EventFragment;
}

export interface StakeEventObject {
  who: string;
  underlying: string;
  sender: string;
  newAmount: BigNumber;
}
export type StakeEvent = TypedEvent<
  [string, string, string, BigNumber],
  StakeEventObject
>;

export type StakeEventFilter = TypedEventFilter<StakeEvent>;

export interface EulStakes extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EulStakesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    eul(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    stake(
      ops: EulStakes.StakeOpStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakeGift(
      beneficiary: string,
      underlying: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakePermit(
      ops: EulStakes.StakeOpStruct[],
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    staked(
      account: string,
      underlying: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  eul(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  stake(
    ops: EulStakes.StakeOpStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakeGift(
    beneficiary: string,
    underlying: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakePermit(
    ops: EulStakes.StakeOpStruct[],
    value: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  staked(
    account: string,
    underlying: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    eul(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    stake(
      ops: EulStakes.StakeOpStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    stakeGift(
      beneficiary: string,
      underlying: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stakePermit(
      ops: EulStakes.StakeOpStruct[],
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    staked(
      account: string,
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Stake(address,address,address,uint256)"(
      who?: string | null,
      underlying?: string | null,
      sender?: null,
      newAmount?: null
    ): StakeEventFilter;
    Stake(
      who?: string | null,
      underlying?: string | null,
      sender?: null,
      newAmount?: null
    ): StakeEventFilter;
  };

  estimateGas: {
    eul(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    stake(
      ops: EulStakes.StakeOpStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakeGift(
      beneficiary: string,
      underlying: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakePermit(
      ops: EulStakes.StakeOpStruct[],
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    staked(
      account: string,
      underlying: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    eul(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stake(
      ops: EulStakes.StakeOpStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakeGift(
      beneficiary: string,
      underlying: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakePermit(
      ops: EulStakes.StakeOpStruct[],
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    staked(
      account: string,
      underlying: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
